# Copyright 2026 The OpenGrm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_python//python:py_binary.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])

exports_files([
    "chatspeak_lexicon.tsv",
    "tokenizer_testdata.tsv",
])

# Language model for chatspeak, for illustration purposes only, since Oscar
# Wilde is not a very good basis for this.
py_binary(
    name = "make_chatspeak_lm",
    srcs = ["make_chatspeak_lm.py"],
    data = [
        "//opengrm/ngram:ngramcount",
        "//opengrm/ngram:ngraminfo",
        "//opengrm/ngram:ngrammake",
        "//opengrm/ngram:ngramsymbols",
        "//opengrm/ngram:testdata",
        "@com_google_openfst//openfst/extensions/far:farcompilestrings",
    ],
    deps = [
        "@com_google_absl_py//absl:app",
        "@com_google_absl_py//absl/flags",
        "@com_google_absl_py//absl/logging",
        "@rules_python//python/runfiles",
    ],
)

genrule(
    name = "earnest_lm",
    outs = ["earnest.fst"],
    cmd = "$(location :make_chatspeak_lm) $(OUTS)",
    tools = [
        ":make_chatspeak_lm",
    ],
)
