nobase_include_HEADERS = baumwelch/baumwelch.h         \
                         baumwelch/cascade.h           \
                         baumwelch/data.h              \
                         baumwelch/decode.h            \
                         baumwelch/expectation-table.h \
                         baumwelch/forward-backward.h  \
                         baumwelch/getters.h           \
                         baumwelch/train.h             \
                         baumwelch/util.h              \
                         baumwelch/decodescript.h      \
                         baumwelch/summation.h         \
                         baumwelch/trainscript.h
