nobase_include_HEADERS = baumwelch/a-star.h            \
                         baumwelch/baumwelch.h         \
                         baumwelch/cascade.h           \
                         baumwelch/decode.h            \
                         baumwelch/expectation-table.h \
                         baumwelch/log-adder.h         \
                         baumwelch/randomize.h         \
                         baumwelch/train.h             \
                         baumwelch/util.h              \
                         baumwelch/decodescript.h      \
                         baumwelch/randomizescript.h   \
                         baumwelch/trainscript.h
