// Copyright 2026 The OpenGrm Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Unit test for RandGen selector/sampler classes for stochastic FSTs.

#include "openfst/lib/randgen.h"

#include <memory>
#include <random>
#include <string>

#include "openfst/compat/file_path.h"
#include "gtest/gtest.h"
#include "absl/flags/flag.h"
#include "absl/log/flags.h"
#include "absl/strings/str_cat.h"
#include "openfst/lib/arc-map.h"
#include "openfst/lib/arc.h"
#include "openfst/lib/determinize.h"
#include "openfst/lib/equal.h"
#include "openfst/lib/rmepsilon.h"
#include "openfst/lib/test-properties.h"
#include "openfst/lib/vector-fst.h"
#include "openfst/lib/verify.h"
#include "opengrm/sfst/normalize.h"
#include "opengrm/sfst/randgen.h"

ABSL_FLAG(bool, regenerate_goldens, false,
          "If true, regenerate the golden fst files.");

namespace sfst {

typedef fst::StdArc Arc;
typedef Arc::StateId StateId;
typedef Arc::Weight Weight;
typedef Arc::Label Label;

class RandGenTest : public testing::Test {
 protected:
  static std::string RandFileN(const int n) {
    return fst::JoinPath(
        std::string("."), "opengrm/sfst/testdata",
        absl::StrCat("rand", n, ".fst"));
  }

  void SetUp() override {
    rfst1_.reset(fst::VectorFst<Arc>::Read(RandFileN(1)));
    rfst2_.reset(fst::VectorFst<Arc>::Read(RandFileN(2)));
    rfst3_.reset(fst::VectorFst<Arc>::Read(RandFileN(3)));
    rfst4_.reset(fst::VectorFst<Arc>::Read(RandFileN(4)));
    rfst5_.reset(fst::VectorFst<Arc>::Read(RandFileN(5)));
    rfst6_.reset(fst::VectorFst<Arc>::Read(RandFileN(6)));
  }

  std::unique_ptr<fst::VectorFst<Arc>> rfst1_;
  std::unique_ptr<fst::VectorFst<Arc>> rfst2_;
  std::unique_ptr<fst::VectorFst<Arc>> rfst3_;
  std::unique_ptr<fst::VectorFst<Arc>> rfst4_;
  std::unique_ptr<fst::VectorFst<Arc>> rfst5_;
  std::unique_ptr<fst::VectorFst<Arc>> rfst6_;
};

TEST_F(RandGenTest, RandGen1) {
  ASSERT_TRUE(IsNormalized(*rfst1_, 0));
  fst::VectorFst<Arc> paths;
  SFstArcSelector<Arc> selector(0);
  fst::RandGenOptions<SFstArcSelector<Arc>> opts(selector);
  opts.npath = 10;
  opts.weighted = true;
  // This is a golden test and we need deterministic output.
  std::mt19937_64 bit_gen;
  fst::RandGen(*rfst1_, &paths, opts, bit_gen);
  ASSERT_TRUE(fst::Verify(paths));
  if (absl::GetFlag(FLAGS_regenerate_goldens)) {
    ASSERT_TRUE(paths.Write(RandFileN(2)));
    rfst2_.reset(fst::VectorFst<Arc>::Read(RandFileN(2)));
  }
  EXPECT_TRUE(fst::Equal(*rfst2_, paths));
}

TEST_F(RandGenTest, RandGen3) {
  // Generate 10,000 paths, map to log semiring, determinize, and compare
  // with delta.
  ASSERT_TRUE(IsNormalized(*rfst3_, 0));
  fst::VectorFst<Arc> paths;
  SFstArcSelector<Arc> selector(0);
  fst::RandGenOptions<SFstArcSelector<Arc>> opts(selector);
  opts.npath = 10000;
  opts.weighted = true;
  std::mt19937_64 bit_gen;  // Deterministic output.
  fst::RandGen(*rfst3_, &paths, opts, bit_gen);
  ASSERT_TRUE(fst::Verify(paths));
  if (absl::GetFlag(FLAGS_regenerate_goldens)) {
    ASSERT_TRUE(paths.Write(RandFileN(4)));
    rfst4_.reset(fst::VectorFst<Arc>::Read(RandFileN(4)));
  }

  fst::VectorFst<fst::LogArc> log_paths;
  fst::ArcMap(paths, &log_paths, fst::StdToLogMapper());
  fst::VectorFst<fst::LogArc> det_paths;
  fst::Determinize(log_paths, &det_paths);

  fst::VectorFst<fst::LogArc> log_gold;
  fst::ArcMap(*rfst4_, &log_gold, fst::StdToLogMapper());
  fst::VectorFst<fst::LogArc> det_gold;
  fst::Determinize(log_gold, &det_gold);

  EXPECT_TRUE(fst::Equal(det_gold, det_paths, 0.04));
}

// Tests if the samples generated by fst and phi-removed fst are similar.
TEST_F(RandGenTest, PhiRemoval) {
  ASSERT_TRUE(IsNormalized(*rfst5_, 0));
  fst::VectorFst<Arc> paths1;
  SFstArcSelector<Arc> selector(0);
  fst::RandGenOptions<SFstArcSelector<Arc>> opts(selector);
  opts.npath = 100000;
  opts.weighted = false;
  std::mt19937_64 gen5;
  fst::RandGen(*rfst5_, &paths1, opts, gen5);
  ASSERT_TRUE(fst::Verify(paths1));
  fst::VectorFst<fst::LogArc> logpaths1;
  fst::ArcMap(paths1, &logpaths1, fst::StdToLogMapper());
  fst::RmEpsilon(&logpaths1);
  fst::VectorFst<fst::LogArc> determinized1;
  fst::Determinize(logpaths1, &determinized1);

  ASSERT_TRUE(IsNormalized(*rfst6_, 0));
  fst::VectorFst<Arc> paths2;
  std::mt19937_64 gen6;
  fst::RandGen(*rfst6_, &paths2, opts, gen6);
  ASSERT_TRUE(fst::Verify(paths2));
  fst::VectorFst<fst::LogArc> logpaths2;
  fst::ArcMap(paths2, &logpaths2, fst::StdToLogMapper());
  fst::VectorFst<fst::LogArc> determinized2;
  fst::Determinize(logpaths2, &determinized2);
  ASSERT_TRUE(fst::Equal(determinized1, determinized2, 0.02));
}

}  // namespace sfst

int main(int argc, char** argv) {
  absl::SetFlag(&FLAGS_fst_verify_properties, true);
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
