nobase_include_HEADERS = sfst/approx.h \
                         sfst/backoff.h \
                         sfst/canonical.h \
                         sfst/count.h \
                         sfst/equal.h \
                         sfst/ngramapprox.h \
                         sfst/normalize.h \
                         sfst/perplexity.h \
                         sfst/phi2matcher.h \
                         sfst/randgen.h \
                         sfst/rmphi.h \
                         sfst/sfst.h \
                         sfst/sfstlib.h \
                         sfst/shortest-distance.h \
                         sfst/state-weights.h \
                         sfst/stationary-distrib.h \
                         sfst/topology.h \
                         sfst/trim.h
