# Copyright 2026 The OpenGrm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("@com_google_protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@com_google_protobuf//bazel:proto_library.bzl", "proto_library")
load("@com_google_protobuf//bazel:py_proto_library.bzl", "py_proto_library")
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//net/proto2/util/public:proto2_db.bzl", "proto2_db")
load("//opengrm/testing:build_defs.bzl", "grm_textproto_test")
load("//opengrm/thrax:grm_build_defs.bzl", "compile_grm")

package(default_visibility = ["//visibility:public"])

exports_files(["build_defs.bzl"])

bzl_library(
    name = "build_defs",
    srcs = ["build_defs.bzl"],
    deps = ["@rules_cc//cc:core_rules"],
)

proto_library(
    name = "testdata_proto",
    srcs = ["testdata.proto"],
    features = ["disable_pbh"],
    option_deps = ["@com_google_protobuf//:cpp_features_proto"],
)

cc_proto_library(
    name = "testdata_cc_proto",
    deps = [":testdata_proto"],
)

py_proto_library(
    name = "testdata_py_proto",
    deps = [":testdata_proto"],
)

proto2_db(
    name = "testdata_proto_db",
    srcs = [":testdata_proto"],
)

# Tests testdata for correctness w.r.t. to grammars.
cc_library(
    name = "test_textproto_lib",
    testonly = 1,
    srcs = ["test_textproto.cc"],
    deps = [
        ":testdata_cc_proto",
        "//opengrm/compat:file",
        "//opengrm/rewrite:rule_cascade",
        "@com_google_absl//absl/algorithm:container",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/log:check",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_googletest//:gtest",
        "@com_google_openfst//openfst/compat:file_path",
        "@com_google_openfst//openfst/lib:string",
        "@com_google_openfst//openfst/script",
        "@com_google_protobuf//:protobuf",
        "@com_google_protobuf//:protobuf_lite",
    ],
    # We use alwayslink = 1 in order to allow our tests to be
    # marked as linkstatic = 1. This allows us to decrease the
    # amount of test time spent on TAP.
    alwayslink = 1,
)

# Use this if you want to actually run this test from a sh_test.
cc_binary(
    name = "test_textproto",
    testonly = 1,
    linkstatic = 1,
    deps = [
        ":test_textproto_lib",
        "@com_google_googletest//:gtest",
    ],
)

compile_grm(
    name = "test_grammar",
    src = "test_grammar.grm",
)

grm_textproto_test(
    name = "build_defs_test",
    grammar = ":test_grammar",
)
