# Copyright 2026 The OpenGrm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# See https://github.com/actions/runner-images.

name: "Bazel (x64 Linux)"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{github.workflow }}-${{github.head_ref || github.ref}}
  cancel-in-progress: ${{github.ref != 'main'}}

# This gives read-only access to the token.
permissions: read-all

jobs:
    build-and-test-x64-linux-bazel:
      runs-on: ubuntu-latest
      timeout-minutes: 120
      env:
        USE_BAZEL_VERSION: 9.1.1
      steps:
        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
          with:
            persist-credentials: false
        - name: Setup Bazel
          uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86 # 0.19.0
          with:
            # Avoid downloading Bazel every time.
            bazelisk-cache: true
            # Store build cache per workflow. In addition to default files
            # (MODULE.bazel, WORKSPACE, BUILD.bazel) hashed by setup-bazel,
            # explicitly include .bazelrc and .bzl files in the cache key.
            disk-cache: ${{github.workflow}}-${{hashFiles('.bazelrc', '**/*.bzl')}}
            # Share repository cache between workflows.
            repository-cache: true
        - name: Check Bazelisk
          run: bazelisk --version
        - name: Build
          run: |
            bazelisk build --config=dev -c fastbuild //...
        - name: Test
          run: >-
            bazelisk test --config=dev -c fastbuild
            --test_size_filters=-enormous --test_output=errors
            //...
